# Generated by Django 6.1 on 2026-08-25 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_orderitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', '🟡 Chờ xác nhận'), ('confirmed', '🔵 Đã xác nhận'), ('shipping', '🟣 Đang giao'), ('completed', '🟢 Đã giao'), ('cancelled', '🔴 Đã hủy')], default='pending', max_length=20),
        ),
    ]
