# Generated by Django 6.1 on 2026-08-25 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', '🟡 Chờ xác nhận'), ('confirmed', '🔵 Đã xác nhận'), ('shipping', '🟣 Đang giao'), ('completed', '🟢 Đã giao'), ('cancelled', '🔴 Đã hủy')], default='pending', max_length=20, verbose_name='Trạng thái'),
        ),
    ]
