# Generated by Django 6.1 on 2026-09-08 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.TextField(blank=True, default='', verbose_name='Ghi chú'),
        ),
    ]
